![imagen](./img/ejercicios.png)

## Ejercicio 1
Importa el módulo de `numpy` y obtén su versión.

In [1]:
import numpy as np
np.__version__

'2.4.2'

## Ejercicio 2
Crea un array de una dimensión que vaya de 0 a 9. Llamalo `my_array`

In [2]:
my_array = np.array([1,2,3,4,5,6,7,8,9])

## Ejercicio 3
Crea un array 3x3, que sea todo a True

In [3]:
array_33_true = np.array([[True, True, True],
                          [True, True, True],
                          [True, True, True]])
print(array_33_true)


[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [4]:
# opción 2, encontré esta idea en internet:

array_33_true = np.ones((3,3), dtype=bool)
print(array_33_true)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


## Ejercicio 4
Extrae todos los impares de `my_array`

In [5]:
array_imp = my_array[my_array % 2 != 0]
print(array_imp)

[1 3 5 7 9]


## Ejercicio 5
En un nuevo array, sustituye todos los impares de `my_array` por -1

In [6]:
new_array_5 = my_array.copy() # hago la copia para que no modifique el array originar
new_array_5[new_array_5 % 2 != 0] = -1
print(new_array_5)

[-1  2 -1  4 -1  6 -1  8 -1]


## Ejercicio 6
En un nuevo array, sustituye todos los impares de `my_array` por -1. Esta vez usa `where`

In [7]:
new_array_6 = np.where(my_array % 2 != 0, -1, my_array)
print(new_array_6)

[-1  2 -1  4 -1  6 -1  8 -1]


## Ejercicio 7
Convierte `my_array` en un nuevo array de dos dimensiones mediante `reshape`.

In [8]:
new_array_7 = my_array.reshape(3,3)
print(new_array_7)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Ejercicio 8
Concatena los siguientes arrays verticalmente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [9]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)

array_concat_8 = np.vstack((a, b))
print(array_concat_8)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


## Ejercicio 9
Concatena los siguientes arrays horizontamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [11]:
a_9 = np.arange(10).reshape(2,-1)
b_9 = np.repeat(1,10).reshape(2,-1)

array_concat_9 = np.hstack((a_9, b_9))
print(array_concat_9)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


## Ejercicio 10
Encuentra todos los elementos en común entre ambos arrays. [Para ello usa la función `intersect1d`](https://numpy.org/doc/stable/reference/generated/numpy.intersect1d.html)

```Python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

In [13]:
a_10 = np.array([1,2,3,2,3,4,3,4,5,6])
b_10 = np.array([7,2,10,2,7,4,9,4,9,8])

array_comun = np.intersect1d(a_10, b_10)
print(array_comun)

[2 4]


## Ejercicio 11
Obtén la documentación acerca de la función `concatenate`

In [14]:
help(np.concatenate)

Help on _ArrayFunctionDispatcher in module numpy:

concatenate(arrays, /, axis=0, out=None, *, dtype=None, casting='same_kind')
    Join a sequence of arrays along an existing axis.
    
    Parameters
    ----------
    a1, a2, ... : sequence of array_like
        The arrays must have the same shape, except in the dimension
        corresponding to `axis` (the first, by default).
    axis : int, optional
        The axis along which the arrays will be joined.  If axis is None,
        arrays are flattened before use.  Default is 0.
    out : ndarray, optional
        If provided, the destination to place the result. The shape must be
        correct, matching that of what concatenate would have returned if no
        out argument were specified.
    dtype : str or dtype
        If provided, the destination array will have this dtype. Cannot be
        provided together with `out`.
    
        .. versionadded:: 1.20.0
    
    casting : {'no', 'equiv', 'safe', 'same_kind', 'unsafe'}, 

## Ejercicio 12
Crea un array unidimensional que vaya del 0 al 9. Llámalo `my_array`. 
1. Multiplica cada uno de los elementos de `my_array` por 10, en un nuevo array
2. Accede al primer elemento de `my_array`
3. Accede al último elemento de `my_array`
4. Imprime por pantalla los numeros del 1 al 7 de `my_array`

In [15]:
my_array_12 = np.array([0,1,2,3,4,5,6,7,8,9])

# 1:
new_array_12 = my_array_12 * 10
print(new_array_12)

# 2:
primer_elemento = my_array_12[0]
print(primer_elemento)

# 3:
ultimo_elemento = my_array_12[-1]
print(ultimo_elemento)

# 4:
otro_array = my_array_12[1:8]
print(otro_array)

[ 0 10 20 30 40 50 60 70 80 90]
0
9
[1 2 3 4 5 6 7]


## Ejercicio 13
Crea un array manualmente de tres filas por tres columnas. Llámalo `my_matrix`

In [18]:
my_matrix = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])

print(my_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Ejercicio 14
Obtén la siguiente secuencia:

```Python
[ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49]
```

In [20]:
secuencia = np.arange(1, 50, 3) # el inicial es el 1 y el último 49 y van aumentando de 3 en 3, así que (1, 50, 3)
print(secuencia)

[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49]


## Ejercicio 15
Obtén la siguiente secuencia

```Python
[4., 3.75, 3.5 , 3.25, 3.  , 2.75, 2.5 , 2.25, 2., 1.75, 1.5 ,1.25]
```

In [21]:
# array que empieza en 4 y va bajando de 0.25 en 0.25 hasta 1.25
secuencia_15 = np.arange(4, 1, -0.25)
print(secuencia_15)

[4.   3.75 3.5  3.25 3.   2.75 2.5  2.25 2.   1.75 1.5  1.25]


## Ejercicio 16
Lee la imagen "numpy.png" usando Pillow, y guárdala en un array.

In [23]:
from PIL import Image

img = Image.open("numpy.png")
img_array = np.array(img)

print(img_array)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  ...
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  ...
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  ...
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 ...

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  ...
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  ...
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  ...
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [ ]:
print(img_array.shape) # dimensiones (alto, ancho, canales)
print(img_array.dtype) # tipo de dato

(306, 765, 4)
uint8


## Ejercicio 17
Crea un array de 4x1. A continuación convierte el array a un 2x2

In [25]:
x = np.array([[1], # creo unarray de 4x1
              [2],
              [3],
              [4]])


y = x.reshape(2,2) # lo convierto en un 2x2
print(y)

[[1 2]
 [3 4]]


## Ejercicio 18
Crea una secuencia aleatoria. La secuencia se tiene que componer de 4 matrices de 5x3. Serían 3 dimensiones diferentes.

In [26]:
secuencia_aleatoria = np.random.random(4*5*3).reshape(4,5,3)
print(secuencia_aleatoria)

[[[0.26651245 0.48622802 0.80536988]
  [0.35302914 0.43100769 0.26711393]
  [0.74899743 0.42729274 0.80821902]
  [0.97800993 0.42147447 0.31156917]
  [0.12351542 0.44888596 0.78906232]]

 [[0.39910522 0.87457254 0.25822837]
  [0.25000961 0.22941122 0.92714595]
  [0.50200111 0.22779845 0.69824493]
  [0.66720249 0.08172695 0.78448578]
  [0.11091468 0.58927999 0.23007401]]

 [[0.03569135 0.44341014 0.2687868 ]
  [0.22212027 0.24119062 0.66849746]
  [0.31499934 0.70862932 0.10208038]
  [0.11295941 0.74196656 0.14019486]
  [0.28588642 0.28599591 0.39673013]]

 [[0.18285455 0.89320461 0.96839906]
  [0.52145702 0.75663483 0.76593079]
  [0.75702374 0.61408641 0.07000061]
  [0.61871911 0.87783453 0.74844565]
  [0.56731412 0.08763635 0.15328892]]]


## Ejercicio 19
Crea una matriz de 10x1, toda ella compuesta por `False`. Después transformalo en un 2x5

In [29]:
w = np.full((10,1), False) # matriz 10x1 con False
print(w)

z = w.reshape(2,5) #reorganizo a 2×5 
print(z)

[[False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]]
[[False False False False False]
 [False False False False False]]


## Ejercicio 20
Dado el siguiente array

```Python
x = np.random.randint(10, 20, size = (5,2,6))
```

1. ¿Cuántos elementos tiene el array?
2. ¿Cuántas dimensiones?
3. ¿Cuánta es la longitud cada dimensión?

In [30]:
x = np.random.randint(10, 20, size = (5,2,6))

# 1:
print(x.size)

# 2:
print(x.ndim)

# 3:
print(x.shape)
# la longitud primera dimensión: 5
# la longitud segunda dimensión: 2
# la longitud tercera dimensión: 6

60
3
(5, 2, 6)
