![imagen](./img/ejercicios.png)

## Ejercicio 1
Importa el módulo de `numpy` y obtén su versión.

In [1]:
import numpy as np
print(np.__version__)

2.4.2


## Ejercicio 2
Crea un array de una dimensión que vaya de 0 a 9. Llamalo `my_array`

In [2]:
my_array = np.array([1,2,3,4,5,6,7,8,9])

## Ejercicio 3
Crea un array 3x3, que sea todo a True

In [3]:
array_33_true = np.array([[True, True, True],
                          [True, True, True],
                          [True, True, True]])
print(array_33_true)


[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [4]:
# opción 2, encontré esta idea en internet:

array_33_true = np.ones((3,3), dtype=bool)
print(array_33_true)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [6]:
# alejandro
triplete = np.array(my_array[0:-1] >= 0)
print(triplete.reshape(3,3))

ValueError: cannot reshape array of size 8 into shape (3,3)

In [ ]:
# ruben
array= np.full((3,3), True)
print(array)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


## Ejercicio 4
Extrae todos los impares de `my_array`

In [5]:
array_imp = my_array[my_array % 2 != 0]
print(array_imp)

[1 3 5 7 9]


In [ ]:
# alejandro
my_array = np.arange(10)
masc_imp = np.array(my_array %2 ==1)
impares = np.array(my_array[masc_imp])
print(masc_imp)
print(impares)

[False  True False  True False  True False  True False  True]
[1 3 5 7 9]


In [8]:
# alejandro
my_array = np.arange(10)
impares = np.array(my_array[1:10:2])
print(impares)

[1 3 5 7 9]


## Ejercicio 5
En un nuevo array, sustituye todos los impares de `my_array` por -1

In [11]:
new_array_5 = my_array.copy() # hago la copia para que no modifique el array originar
new_array_5[new_array_5 % 2 != 0] = -1
print(new_array_5)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [ ]:
# alejandro
two_array = np.where(masc_imp, -1, my_array)
print(two_array)
print(my_array)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]


## Ejercicio 6
En un nuevo array, sustituye todos los impares de `my_array` por -1. Esta vez usa `where`

In [7]:
new_array_6 = np.where(my_array % 2 != 0, -1, my_array)
print(new_array_6)

[-1  2 -1  4 -1  6 -1  8 -1]


## Ejercicio 7
Convierte `my_array` en un nuevo array de dos dimensiones mediante `reshape`.

In [13]:
new_array_7 = my_array.reshape(2,5)
print(new_array_7)

[[0 1 2 3 4]
 [5 6 7 8 9]]


## Ejercicio 8
Concatena los siguientes arrays verticalmente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [9]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)

array_concat_8 = np.vstack((a, b))
print(array_concat_8)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [15]:
# urko:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)

array_concat_8 = np.concatenate((a, b)) # sale lo mismo porque la concatenacion por defecto en np es por fila
print(array_concat_8)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


## Ejercicio 9
Concatena los siguientes arrays horizontamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [11]:
a_9 = np.arange(10).reshape(2,-1)
b_9 = np.repeat(1,10).reshape(2,-1)

array_concat_9 = np.hstack((a_9, b_9))
print(array_concat_9)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [16]:
array_concat_9 = np.concatenate((a, b), axis=1)
print(array_concat_9)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


## Ejercicio 10
Encuentra todos los elementos en común entre ambos arrays. [Para ello usa la función `intersect1d`](https://numpy.org/doc/stable/reference/generated/numpy.intersect1d.html)

```Python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

In [13]:
a_10 = np.array([1,2,3,2,3,4,3,4,5,6])
b_10 = np.array([7,2,10,2,7,4,9,4,9,8])

array_comun = np.intersect1d(a_10, b_10)
print(array_comun)

[2 4]


## Ejercicio 11
Obtén la documentación acerca de la función `concatenate`

In [14]:
help(np.concatenate)

Help on _ArrayFunctionDispatcher in module numpy:

concatenate(arrays, /, axis=0, out=None, *, dtype=None, casting='same_kind')
    Join a sequence of arrays along an existing axis.
    
    Parameters
    ----------
    a1, a2, ... : sequence of array_like
        The arrays must have the same shape, except in the dimension
        corresponding to `axis` (the first, by default).
    axis : int, optional
        The axis along which the arrays will be joined.  If axis is None,
        arrays are flattened before use.  Default is 0.
    out : ndarray, optional
        If provided, the destination to place the result. The shape must be
        correct, matching that of what concatenate would have returned if no
        out argument were specified.
    dtype : str or dtype
        If provided, the destination array will have this dtype. Cannot be
        provided together with `out`.
    
        .. versionadded:: 1.20.0
    
    casting : {'no', 'equiv', 'safe', 'same_kind', 'unsafe'}, 

In [18]:
np.concatenate?

Signature:      
np.concatenate(
    arrays,
    /,
    axis=0,
    out=None,
    *,
    dtype=None,
    casting='same_kind',
)
Call signature:  np.concatenate(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <built-in function concatenate>
Docstring:      
Join a sequence of arrays along an existing axis.

Parameters
----------
a1, a2, ... : sequence of array_like
    The arrays must have the same shape, except in the dimension
    corresponding to `axis` (the first, by default).
axis : int, optional
    The axis along which the arrays will be joined.  If axis is None,
    arrays are flattened before use.  Default is 0.
out : ndarray, optional
    If provided, the destination to place the result. The shape must be
    correct, matching that of what concatenate would have returned if no
    out argument were specified.
dtype : str or dtype
    If provided, the destination array will have this dtype. Cannot be
    provided together with `out`.

    .. versiona

In [17]:
print(np.concatenate.__doc__)

Join a sequence of arrays along an existing axis.

Parameters
----------
a1, a2, ... : sequence of array_like
    The arrays must have the same shape, except in the dimension
    corresponding to `axis` (the first, by default).
axis : int, optional
    The axis along which the arrays will be joined.  If axis is None,
    arrays are flattened before use.  Default is 0.
out : ndarray, optional
    If provided, the destination to place the result. The shape must be
    correct, matching that of what concatenate would have returned if no
    out argument were specified.
dtype : str or dtype
    If provided, the destination array will have this dtype. Cannot be
    provided together with `out`.

    .. versionadded:: 1.20.0

casting : {'no', 'equiv', 'safe', 'same_kind', 'unsafe'}, optional
    Controls what kind of data casting may occur. Defaults to 'same_kind'.
    For a description of the options, please see :term:`casting`.

    .. versionadded:: 1.20.0

Returns
-------
res : ndarray
 

## Ejercicio 12
Crea un array unidimensional que vaya del 0 al 9. Llámalo `my_array`. 
1. Multiplica cada uno de los elementos de `my_array` por 10, en un nuevo array
2. Accede al primer elemento de `my_array`
3. Accede al último elemento de `my_array`
4. Imprime por pantalla los numeros del 1 al 7 de `my_array`

In [15]:
my_array_12 = np.array([0,1,2,3,4,5,6,7,8,9])

# 1:
new_array_12 = my_array_12 * 10
print(new_array_12)

# 2:
primer_elemento = my_array_12[0]
print(primer_elemento)

# 3:
ultimo_elemento = my_array_12[-1]
print(ultimo_elemento)

# 4:
otro_array = my_array_12[1:8]
print(otro_array)

[ 0 10 20 30 40 50 60 70 80 90]
0
9
[1 2 3 4 5 6 7]


In [ ]:
# alejandro:
my_array= np.arange(10)

decenas = my_array *10
print(decenas)

print(my_array[0])
print(my_array[-1])
print(my_array[1:8])

[ 0 10 20 30 40 50 60 70 80 90]
0
9
[1 2 3 4 5 6 7]


## Ejercicio 13
Crea un array manualmente de tres filas por tres columnas. Llámalo `my_matrix`

In [21]:
my_matrix = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])

print(my_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
import pprint
pprint.pprint(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])


## Ejercicio 14
Obtén la siguiente secuencia:

```Python
[ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49]
```

In [20]:
secuencia = np.arange(1, 50, 3) # el inicial es el 1 y el último 49 y van aumentando de 3 en 3, así que (1, 50, 3)
print(secuencia)

[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49]


## Ejercicio 15
Obtén la siguiente secuencia

```Python
[4., 3.75, 3.5 , 3.25, 3.  , 2.75, 2.5 , 2.25, 2., 1.75, 1.5 ,1.25]
```

In [21]:
# array que empieza en 4 y va bajando de 0.25 en 0.25 hasta 1.25
secuencia_15 = np.arange(4, 1, -0.25)
print(secuencia_15)

[4.   3.75 3.5  3.25 3.   2.75 2.5  2.25 2.   1.75 1.5  1.25]


## Ejercicio 16
Lee la imagen "numpy.png" usando Pillow, y guárdala en un array.

In [30]:
from PIL import Image

img = Image.open("numpy.png")

img_array = np.array(img) # imagen guardada en un array

print(type(img_array))
print(img_array)

print(img_array.shape) # sale un 4 porque los png tienen un canal de transparencia

<class 'numpy.ndarray'>
[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  ...
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  ...
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  ...
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 ...

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  ...
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  ...
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  ...
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
(306, 765, 4)


In [ ]:
print(img_array.shape) # dimensiones (alto, ancho, canales)
print(img_array.dtype) # tipo de dato

(306, 765, 4)
uint8


## Ejercicio 17
Crea un array de 4x1. A continuación convierte el array a un 2x2

In [25]:
x = np.array([[1], # creo unarray de 4x1
              [2],
              [3],
              [4]])


y = x.reshape(2,2) # lo convierto en un 2x2
print(y)

[[1 2]
 [3 4]]


In [35]:
cuaternario = np.arange(4).reshape(4,1) # np arrange 
print(cuaternario)
print(cuaternario.reshape(2,2))

[[0]
 [1]
 [2]
 [3]]
[[0 1]
 [2 3]]


## Ejercicio 18
Crea una secuencia aleatoria. La secuencia se tiene que componer de 4 matrices de 5x3. Serían 3 dimensiones diferentes.

In [44]:
# esta podría dar errores al meter a mano 4*5*3
secuencia_aleatoria = np.random.random(4*5*3).reshape(4,5,3) # es in size, quiero 60 elementos randome y reoganiza en 4*5*3

print(secuencia_aleatoria)

[[[0.9755521  0.78589518 0.96162352]
  [0.31472813 0.96227155 0.25082294]
  [0.66241486 0.1395777  0.88744061]
  [0.37914696 0.65434396 0.81877956]
  [0.93333498 0.50459902 0.36339899]]

 [[0.21146176 0.68806175 0.62746947]
  [0.59210989 0.83598238 0.6177977 ]
  [0.45094786 0.45342523 0.31813978]
  [0.21573327 0.64398777 0.95889516]
  [0.76842447 0.51991118 0.7485231 ]]

 [[0.3676068  0.51000021 0.35204213]
  [0.15798705 0.69755307 0.63948163]
  [0.1915058  0.76862375 0.06174724]
  [0.38262574 0.18496243 0.8759921 ]
  [0.77094851 0.01507781 0.03691065]]

 [[0.15223081 0.32607397 0.17649427]
  [0.32429859 0.1075939  0.34728367]
  [0.46583871 0.27877862 0.56725784]
  [0.55076297 0.32912858 0.27029258]
  [0.27945759 0.07155972 0.35849221]]]


In [42]:
aleta = np.random.randint(0, 40, (4, 5, 3))
print(aleta)

[[[26  6 28]
  [10 18 20]
  [35  0 16]
  [22 15 30]
  [ 3 20  6]]

 [[35 17 36]
  [33 38 36]
  [20  5 22]
  [16 26  2]
  [25  2 18]]

 [[ 6  2 10]
  [32  7 12]
  [19 28 16]
  [15 26 20]
  [ 1 37  4]]

 [[ 5 33 16]
  [23 36 15]
  [10 33 19]
  [ 3 26 32]
  [12 25 14]]]


In [ ]:
# ruben
print(np.random.rand(4, 5, 3))

[[[0.96424051 0.57958612 0.60498105]
  [0.17662063 0.98956817 0.87185623]
  [0.09832612 0.16239284 0.70200638]
  [0.04131318 0.19396524 0.45857769]
  [0.69510003 0.72251463 0.59625135]]

 [[0.36704761 0.36819426 0.62749665]
  [0.50111841 0.98782875 0.2805818 ]
  [0.08031489 0.78553317 0.79265187]
  [0.94903275 0.9020972  0.34305036]
  [0.65169647 0.54532975 0.76386896]]

 [[0.82713009 0.77298734 0.81184968]
  [0.74176291 0.17300585 0.73842091]
  [0.14785457 0.33779047 0.01684959]
  [0.23085032 0.86536741 0.5314124 ]
  [0.9171306  0.93958809 0.02441398]]

 [[0.17507786 0.42434641 0.30890172]
  [0.08126596 0.49493666 0.67549822]
  [0.12502076 0.58962988 0.59639098]
  [0.08232095 0.28980984 0.5655421 ]
  [0.7457625  0.11064481 0.59697442]]]


## Ejercicio 19
Crea una matriz de 10x1, toda ella compuesta por `False`. Después transformalo en un 2x5

In [45]:
w = np.full((10,1), False) # matriz 10x1 con False
print(w)

z = w.reshape(2,5) # reorganizo a 2×5 
print(z)

[[False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]]
[[False False False False False]
 [False False False False False]]


In [ ]:
decano = np.zeros(10, dtype=bool).reshape(2,5)


## Ejercicio 20
Dado el siguiente array

```Python
x = np.random.randint(10, 20, size = (5,2,6))
```

1. ¿Cuántos elementos tiene el array?
2. ¿Cuántas dimensiones?
3. ¿Cuánta es la longitud cada dimensión?

In [ ]:
x = np.random.randint(10, 20, size = (5,2,6))

# 1:
print(x.size)
# 5*2*6 = 60

# 2:
print(x.ndim)

# 3:
print(x.shape)
# la longitud primera dimensión: 5
# la longitud segunda dimensión: 2
# la longitud tercera dimensión: 6

60
3
(5, 2, 6)
