![imagen](./img/ejercicios.png)

In [3]:
import numpy as np

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden, usando numpy.

In [4]:
# 1:
my_array = np.arange(10)
print(my_array)

# 2:
print(my_array[9:0:-2])

[0 1 2 3 4 5 6 7 8 9]
[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [5]:
print(my_array[8:6:-1])

print(my_array[-2:-4:-1])

[8 7]
[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [8]:
print(my_array[2::-1])

print(np.flip(my_array[:3:]))

[2 1 0]
[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [ ]:
# 1:
matriz_4 = np.arange(1, 21).reshape(4, 5)
print(matriz_4)

# 2:
matriz_invertida = matriz_4[::-1, ::-1]
print(matriz_invertida)

# unai
print(np.flip(matriz_4)) # flip le da la vuelta a todo

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]
[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [ ]:
matriz_5 = np.arange(1, 21).reshape(4, 5)
print(matriz_5)

# sin acabar

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [10]:
# unai
print(matriz_4[:2, :2])

[[1 2]
 [6 7]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [14]:
matriz_6 = matriz_4[[0, 2], :][:, [0, 2, 4]]
print(matriz_6)

[[ 1  3  5]
 [11 13 15]]


In [ ]:
# al empezar en 1, si empieza en 0 puede haber movida
matriz_6 = matriz_4[::2, ::2]
print(matriz_6)

[[ 1  3  5]
 [11 13 15]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [14]:
matriz_7 = matriz_4[:3, ::-1]
print(matriz_7)

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [15]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

loros = x[x == "Loro"]
print(loros)

# unai
mask = x == "Loro"
print(x[mask])

['Loro' 'Loro']
['Loro' 'Loro']


In [17]:
# otra opción:
indices = np.where(x == "Loro")
loros = x[indices]
print(loros)

['Loro' 'Loro']


## Ejercicio 9
Crea una secuencia de 20 elementos y transfórmala en un array compuesto por 2 matrices de 5x2

In [18]:
sec_20 = np.arange(20)
print(sec_20)

array_2_matriz = sec_20.reshape(2, 5, 2)
print(array_2_matriz)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


## Ejercicio 10

Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [21]:
array_10 = np.zeros(10)
print("Memoria ocupada:", array_10.nbytes, "bytes")

array_10[3] = 1
print(array_10)

Memoria ocupada: 80 bytes
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


In [16]:
zeros = np.zeros(10, dtype=int)
print(zeros.nbytes)
zeros[3] = 1
print(zeros)

80
[0 0 0 1 0 0 0 0 0 0]


## Ejercicio 11

Crea un vector que vaya del 10 al 49

Inviértelo

In [25]:
array_11 = np.arange(10, 50)
print(array_11)


array_11_invertido = array_11[::-1]
print(array_11_invertido)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [ ]:
# unai
print(np.flip(np.arange(10,50)))

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejercicio 12
Encuentra los índices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [1, 2 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/) Encapsúlalo en una función, con un argumento de entrada de un vector.

In [26]:
array_12 = np.array([1, 2, 0, 0, 4, 0])
print(array_12)

def indices_no_cero(vector):
    return np.nonzero(vector)[0]


print(indices_no_cero(array_12))

[1 2 0 0 4 0]
[0 1 4]


In [19]:
# unai
def non_zero(x):
    return x[x != 0]

print(non_zero(np.array([1,2,0,0,4,0])))

[1 2 4]


## Ejercicio 13
Crea una matriz de números aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [28]:
matriz_13 = np.random.random((10, 10))
print(matriz_13)

min_matriz_13 = matriz_13.min()
max_matriz_13 = matriz_13.max()

print("Mínimo de la matriz:", min_matriz_13)
print("Máximo de la matriz:", max_matriz_13)

[[0.64430256 0.41323228 0.3215687  0.99161535 0.60901089 0.47493673
  0.47927418 0.36982025 0.69744761 0.1007683 ]
 [0.67609874 0.86168523 0.45374523 0.68585609 0.63689267 0.86937373
  0.96744663 0.03375194 0.31642779 0.74066693]
 [0.30558149 0.38348051 0.84084387 0.80216252 0.60294173 0.71329902
  0.8757517  0.99835593 0.8759754  0.24748553]
 [0.93698916 0.25501609 0.05590766 0.92695765 0.52409461 0.51308115
  0.62746541 0.64307055 0.5796152  0.52850967]
 [0.85937044 0.32025187 0.36804184 0.36195399 0.21281215 0.14134258
  0.31300406 0.28041198 0.9519632  0.97228844]
 [0.67843422 0.98111072 0.86491796 0.88226319 0.21766659 0.89848373
  0.83562248 0.1119255  0.35343943 0.05629857]
 [0.1552599  0.53422237 0.47657467 0.90070873 0.85024698 0.56615883
  0.97831616 0.94295355 0.28658507 0.8771261 ]
 [0.01360793 0.30126842 0.73948124 0.40952179 0.89556644 0.2165248
  0.84998757 0.50159625 0.91188604 0.51656498]
 [0.04655578 0.13706425 0.42291755 0.14139641 0.01417737 0.52574757
  0.14061351 

In [25]:
# unai 
rm = np.random.randint(1, 10001, (10,10))
print(rm)
print()
print("Max: %d\nMin: %d" % (np.max(rm), np.min(rm)))

[[8801 6757 4319 9882 7323 5154  402 1481 9103 7016]
 [5370 8074 4539 8807 5626 2668 1203 8478 1503 5811]
 [6243 3376 6637 2410 2122 3365 5237 6038 8309 6357]
 [6758  683 5815 9084 1164 1583 5074  938 2767 4143]
 [8684 4598 7836 7969 4381  593 9122 7384 3591 5603]
 [2112 9733 2283 8292 5763 1631 2594 3718 6126 8214]
 [5216 7818 9849 8600 3641 7853 3068 1378 6922 5007]
 [7863 4461  536  839 7295 3565 8131 6285 1046 3099]
 [2493 5234 8655  226 8339 4492 4358 9516 5741  564]
 [1922  489 5801 2298 5329 2757 6380 5739 9207   62]]

Max: 9882
Min: 62


## Ejercicio 14
Crea un vector aleatorio de tamaño 30 y calcula su media

In [30]:
array_14 = np.random.random(30)

media_array_14 = array_14.mean()

print("Vector:", array_14)
print("Media:", media_array_14)

Vector: [0.57391775 0.23104011 0.47803089 0.06198045 0.93764146 0.89935816
 0.41740095 0.38545206 0.81801038 0.61109389 0.31679068 0.12247165
 0.14990831 0.32704459 0.78817858 0.96939207 0.85213193 0.78867863
 0.18103832 0.93597417 0.24886694 0.78258878 0.75439409 0.99138483
 0.3910699  0.07637621 0.20593016 0.27892961 0.17863495 0.21021797]
Media: 0.4987976159774


In [21]:
# unai
vec = np.random.randint(1, 10001, 30)
print("Media: %.2f" % (vec.mean()))

Media: 4929.07


## Ejercicio 15
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [27]:
# Dimensión del array (puedes cambiarla)
dim_array = 6

# Matriz n×n de ceros
matriz_15 = np.zeros((dim_array, dim_array), dtype=int)

# Asignar 1s al borde
matriz_15[0, :] = 1 # fila superior
matriz_15[-1, :] = 1 # fila inferior
matriz_15[:, 0] = 1 # columna izquierda
matriz_15[:, -1] = 1 # columna derecha

print(matriz_15)

[[1 1 1 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 1 1 1 1 1]]


In [ ]:
m = np.ones((6,6), dtype= int)
m[1:-1, 1:-1] = 0 # quiero que hagas los cambios menos en las filas primera y ultima y lo mismo con las columnas
print(m)

[[1 1 1 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 1 1 1 1 1]]


## Ejercicio 16
Crea una matriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [33]:
# parte de una matriz de ceros y asigna unos en posiciones alternas
matriz_16 = np.zeros((8, 8), dtype=int)

matriz_16[0::2, 1::2] = 1 # filas pares, columnas impares
matriz_16[1::2, 0::2] = 1 # filas impares, columnas pares

print(matriz_16)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [33]:
# unai
matriz_16 = np.ones((8, 8), dtype=int)

matriz_16[::2, ::2] = 0
matriz_16[1::2, 1::2] = 0

print(matriz_16)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [32]:
# suma de índices
matriz_16 = (np.indices((8, 8)).sum(axis=0) % 2).astype(int)
print(matriz_16)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 17
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [36]:
# matriz con base 2×2
matriz_17 = np.array([[0, 1],
                     [1, 0]])

# matriz para formar una matriz 8×8
matriz_17 = np.tile(matriz_17, (4, 4))

print(matriz_17)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [35]:
# fatima
patron2 = np.ones((8,8), dtype=int)
matriz = np.tile([[0,1], [1,0]], (4,4))
print(matriz)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 18
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [37]:
matriz_18 = np.random.random((5, 5))


media_matriz_18 = np.mean(matriz_18)
desv_matriz_18 = np.std(matriz_18)


matriz_18_norm = (matriz_18 - media_matriz_18) / desv_matriz_18

print("Matriz original:\n", matriz_18)
print("\nMedia:", media_matriz_18)
print("Desviación estándar:", desv_matriz_18)
print("\nMatriz normalizada:\n", matriz_18_norm)

Matriz original:
 [[0.73040782 0.24703405 0.95175053 0.20584856 0.40017688]
 [0.60227908 0.55405404 0.91787574 0.27862119 0.32660134]
 [0.18757543 0.56695574 0.67871354 0.21761686 0.2069666 ]
 [0.5012233  0.77927562 0.57360772 0.80786359 0.51909118]
 [0.61753988 0.17489743 0.9899837  0.33599341 0.28398492]]

Media: 0.5062375258841092
Desviación estándar: 0.2525948730438787

Matriz normalizada:
 [[ 0.88746969 -1.02616286  1.76374524 -1.18921245 -0.41988441]
 [ 0.38021971  0.1893012   1.62963802 -0.90111224 -0.71116324]
 [-1.26155408  0.24037786  0.68281678 -1.14262282 -1.18478621]
 [-0.01985088  1.08093285  0.26671245  1.19411001  0.05088644]
 [ 0.44063584 -1.31174514  1.91510687 -0.67398089 -0.87987772]]


In [ ]:
# unai
mat = np.random.randint(0,5, (5,5))

print((mat - mat.mean())/mat.std())

[[ 1.40845911 -0.5846434   0.0797241   0.7440916   1.40845911]
 [ 0.0797241  -1.24901091  0.7440916   0.0797241  -0.5846434 ]
 [-1.24901091  1.40845911  1.40845911  1.40845911 -0.5846434 ]
 [ 0.7440916  -1.24901091  0.0797241  -1.24901091  0.7440916 ]
 [-1.24901091 -1.24901091 -0.5846434   0.7440916  -1.24901091]]


## Ejercicio 19
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [41]:
array_19 = np.arange(0, 11)
print(array_19)

array_19_mod = array_19.copy()
array_19_mod[(array_19_mod >= 3) & (array_19_mod <= 8)] = -1
print(array_19_mod)


array_19_neg = array_19.copy()
array_19_neg[(array_19_neg >= 3) & (array_19_neg <= 8)] *= -1
print(array_19_neg)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]
[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


In [38]:
# fátima
seq = np.arange(11)
array_19_a = np.where((seq > 3) & (seq < 8), -1, seq)
print(array_19_a)

array_19_b = np.where((seq > 3) & (seq < 8), -seq, seq)
print(array_19_b)

[ 0  1  2  3 -1 -1 -1 -1  8  9 10]
[ 0  1  2  3 -4 -5 -6 -7  8  9 10]
